- name: Install shadowsocks-libev build tools and supervisor
  apt: name={{ item }} install_recommends=no update_cache=yes
  with_items:
    - build-essential
    - autoconf
    - libtool
    - libssl-dev
    - libpcre3-dev
    - asciidoc
    - xmlto
    - curl
    - supervisor