---
- name: Download shadowsocks-libev GitHub latest release tag
  shell: curl -Ls -w %{url_effective} -o /dev/null https://github.com/shadowsocks/shadowsocks-libev/releases/latest
  register: ss_release_link
  when: ss_release == "latest"

- name: Override default release if set with latest
  set_fact: ss_release={{ ss_release_link.stdout.split('/')[-1] }}
  when: ss_release == "latest"

- debug: var=ss_release

- name: Create shadowsocks-libev directory
  file: path=/opt/shadowsocks-libev/{{ ss_release }} state=directory mode=0755

- name: Download release
  get_url:
    url: https://github.com/shadowsocks/shadowsocks-libev/archive/{{ ss_release }}.tar.gz
    dest: /opt/shadowsocks-libev/{{ ss_release }}.tar.gz
    mode: 0640
  environment: "{{proxy_env}}"

- name: Unarchive remote source
  unarchive: src=/opt/shadowsocks-libev/{{ ss_release }}.tar.gz dest=/opt/shadowsocks-libev/{{ ss_release }} remote_src=yes

- name: Configure and make
  shell: ./configure && make && make install chdir=/opt/shadowsocks-libev/{{ ss_release }}/shadowsocks-libev-{{ ss_release[1:] }}
